#!/usr/bin/env bash
#
# Builds a read-only "Brightness Level" APK with the plain Android command line
# tools. No Android Studio, no Gradle.
#
# The pipeline is the same one Android Studio runs internally:
#   aapt2 link -> javac -> d8 -> zip -> zipalign -> apksigner
#
set -euo pipefail

SDK="${ANDROID_SDK_ROOT:-/media/Linux/Eos/Linux/android-sdk}"
PLATFORM=35
BUILD_TOOLS=35.0.0
MIN_SDK=26
# JDK 27 defaults to class file v67, which d8 cannot read. Pin to 17.
RELEASE=17

KEYSTORE_NAME=keystore.jks
KS_PASS=brightnesslevel
KEY_ALIAS=brightnesslevel
KEY_PASS=brightnesslevel

ROOT="$(cd "$(dirname "$0")" && pwd)"
BT="$SDK/build-tools/$BUILD_TOOLS"
ANDROID_JAR="$SDK/platforms/android-$PLATFORM/android.jar"
BUILD="$ROOT/build"
DIST="$ROOT/dist"
APK_NAME=hyprduck.apk

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

for tool in "$BT/aapt2" "$BT/d8" "$BT/zipalign" "$BT/apksigner" "$ANDROID_JAR"; do
    [ -e "$tool" ] || { echo "missing: $tool" >&2; exit 1; }
done

step "Clean"
rm -rf "$BUILD"
mkdir -p "$BUILD/classes" "$BUILD/dex" "$BUILD/gen" "$DIST"

step "1/6 aapt2 compile + link"
"$BT/aapt2" compile --dir "$ROOT/res" -o "$BUILD/res.zip"
"$BT/aapt2" link \
    -I "$ANDROID_JAR" \
    --manifest "$ROOT/AndroidManifest.xml" \
    --min-sdk-version "$MIN_SDK" \
    --target-sdk-version "$PLATFORM" \
    --java "$BUILD/gen" \
    -o "$BUILD/base.apk" \
    "$BUILD/res.zip"

step "2/6 javac -> .class"
# R.java is generated by the link step above and lives in the app's own package,
# so it compiles alongside the sources with no import.
javac --release "$RELEASE" \
    -classpath "$ANDROID_JAR" \
    -d "$BUILD/classes" \
    $(find "$ROOT/src" "$BUILD/gen" -name '*.java')

step "3/6 d8 -> classes.dex"
# shellcheck disable=SC2046
"$BT/d8" --release --min-api "$MIN_SDK" --lib "$ANDROID_JAR" \
    --output "$BUILD/dex" \
    $(find "$BUILD/classes" -name '*.class')

step "4/6 Assemble"
cp "$BUILD/base.apk" "$BUILD/unsigned.apk"
( cd "$BUILD/dex" && zip -q -X "$BUILD/unsigned.apk" classes.dex )

step "5/6 zipalign"
"$BT/zipalign" -f -p 4 "$BUILD/unsigned.apk" "$BUILD/aligned.apk"

step "6/6 Sign"
KEYSTORE="$ROOT/$KEYSTORE_NAME"
if [ ! -f "$KEYSTORE" ]; then
    echo "No keystore yet, generating $KEYSTORE_NAME"
    echo "KEEP THIS FILE. Losing it means you must uninstall the app before"
    echo "installing a later build, because Android matches signatures."
    keytool -genkeypair -v \
        -keystore "$KEYSTORE" \
        -storepass "$KS_PASS" -keypass "$KEY_PASS" \
        -alias "$KEY_ALIAS" \
        -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=realvenerable, OU=HyprDuck, O=HyprDuck, C=US" >/dev/null
fi

"$BT/apksigner" sign \
    --ks "$KEYSTORE" \
    --ks-key-alias "$KEY_ALIAS" \
    --ks-pass "pass:$KS_PASS" \
    --key-pass "pass:$KEY_PASS" \
    --v4-signing-enabled false \
    --out "$DIST/$APK_NAME" \
    "$BUILD/aligned.apk"

step "Verify"
"$BT/apksigner" verify --verbose --print-certs "$DIST/$APK_NAME"
"$BT/aapt2" dump badging "$DIST/$APK_NAME" | grep -E '^(package|application-label|sdkVersion|targetSdkVersion|uses-permission)'

printf '\n\033[1;32mBuilt %s (%s)\033[0m\n' "$DIST/$APK_NAME" "$(du -h "$DIST/$APK_NAME" | cut -f1)"
echo "Install with: adb install -r $DIST/$APK_NAME"
